services:

  nginx:
    build:
      context: ./
      target: nginx
    ports:
      - 80:80
    links:
      - channel-server

  channel-server:
    build:
      context: ./channelServer/
      target: production
    command: [ '--log_level=10', '--first_peer' ]
