
volumes:
    logs:

services:

  nginx:
    build:
      context: ./
      target: nginx
    ports:
      - 80:80
    links:
      - channel-server
    volumes:
        - logs:/var/log


  channel-server:
    build:
      context: ./channelServer/
      target: production
    command: [ '--log_level=10', '--first_peer' ]
    ports:         # Only for local development
      - 9800:9800  # Only for local development
