sound_effect_01.mp3:
	for i in {1..9} \
	; do \
		curl -O https://zxnet.co.uk/spectrum/chaos/sounds/sound_effect_0$$i.mp3 \
	; done
	for i in {10..23} \
	; do \
		curl -O https://zxnet.co.uk/spectrum/chaos/sounds/sound_effect_$$i.mp3 \
	; done
	for i in \
		S10 \
		S60 \
		S61 \
		engaged_sound_effect \
	; do \
		curl -O https://zxnet.co.uk/spectrum/chaos/sounds/$$i.mp3 \
	; done \
